command:
  ros__parameters:
    # Controller axes
    yaw: 0
    altitude: 1
    side: 2
    forward: 3
    
    # Controller buttons
    takeoff: 1
    land: 2

    takeoff_altitude: 1.0 # Meters
    max_linear_speed: 5.0
    max_angular_speed: 5.0